### PR TITLE
Added installation command

### PR DESCRIPTION
**Pull request by Restuta**
so people don't have to guess/look it up

### CODE REVIEW

**Comment by Restuta** [comment]
@niieani what do you think about merging this PR?

**Comment by niieani** [comment]
Hi @Restuta. I think it might be good to re-word it a bit, perhaps mention it can be installed with npm or yarn, preferably as a `devDependency`. Would be good to have that as a separate paragraph/step, rather than joined together with the description of the configuration.

**Comment by Restuta** [comment]
@niieani done, 🏓

**Comment by niieani** [comment]
Thanks 👏

**Pull request merged**
